/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Content
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


using System;
using System.Collections.Generic;
using Kandy.Base;
using Kandy.Converters;




namespace Kandy.Rest.Content.V1.Content
{
    /// <summary> Fetch a Content resource's approval status by its unique Content Sid </summary>
    public class FetchApprovalFetchOptions : IOptions<ApprovalFetchResource>
    {

        ///<summary> The Kandy-provided string that uniquely identifies the Content resource whose approval information to fetch. </summary> 
        public string PathSid { get; }



        /// <summary> Construct a new FetchApprovalFetchOptions </summary>
        /// <param name="pathSid"> The Kandy-provided string that uniquely identifies the Content resource whose approval information to fetch. </param>
        public FetchApprovalFetchOptions(string pathSid)
        {
            PathSid = pathSid;
        }


        /// <summary> Generate the necessary parameters </summary>
        public List<KeyValuePair<string, string>> GetParams()
        {
            var p = new List<KeyValuePair<string, string>>();

            return p;
        }


    }


}
