/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Messaging
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Kandy.Base;
using Kandy.Clients;
using Kandy.Converters;
using Kandy.Exceptions;
using Kandy.Http;



namespace Kandy.Rest.Messaging.V1.BrandRegistration
{
    public class BrandRegistrationOtpResource : Resource
    {



        private static Request BuildCreateRequest(CreateBrandRegistrationOtpOptions options, IKandyRestClient client)
        {

            string path = "/v1/a2p/BrandRegistrations/{BrandRegistrationSid}/SmsOtp";

            string PathBrandRegistrationSid = options.PathBrandRegistrationSid;
            path = path.Replace("{" + "BrandRegistrationSid" + "}", PathBrandRegistrationSid);

            return new Request(
                HttpMethod.Post,
                Rest.Domain.Messaging,
                path,
                postParams: options.GetParams(),
                headerParams: null
            );
        }

        /// <summary> create </summary>
        /// <param name="options"> Create BrandRegistrationOtp parameters </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> A single instance of BrandRegistrationOtp </returns>
        public static BrandRegistrationOtpResource Create(CreateBrandRegistrationOtpOptions options, IKandyRestClient client = null)
        {
            client = client ?? KandyClient.GetRestClient();
            var response = client.Request(BuildCreateRequest(options, client));
            return FromJson(response.Content);
        }

#if !NET35
        /// <summary> create </summary>
        /// <param name="options"> Create BrandRegistrationOtp parameters </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> Task that resolves to A single instance of BrandRegistrationOtp </returns>
        public static async System.Threading.Tasks.Task<BrandRegistrationOtpResource> CreateAsync(CreateBrandRegistrationOtpOptions options,
        IKandyRestClient client = null)
        {
            client = client ?? KandyClient.GetRestClient();
            var response = await client.RequestAsync(BuildCreateRequest(options, client));
            return FromJson(response.Content);
        }
#endif

        /// <summary> create </summary>
        /// <param name="pathBrandRegistrationSid"> Brand Registration Sid of Sole Proprietor Brand. </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> A single instance of BrandRegistrationOtp </returns>
        public static BrandRegistrationOtpResource Create(
                                          string pathBrandRegistrationSid,
                                          IKandyRestClient client = null)
        {
            var options = new CreateBrandRegistrationOtpOptions(pathBrandRegistrationSid) { };
            return Create(options, client);
        }

#if !NET35
        /// <summary> create </summary>
        /// <param name="pathBrandRegistrationSid"> Brand Registration Sid of Sole Proprietor Brand. </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> Task that resolves to A single instance of BrandRegistrationOtp </returns>
        public static async System.Threading.Tasks.Task<BrandRegistrationOtpResource> CreateAsync(
                                                                                  string pathBrandRegistrationSid,
                                                                                  IKandyRestClient client = null)
        {
            var options = new CreateBrandRegistrationOtpOptions(pathBrandRegistrationSid) { };
            return await CreateAsync(options, client);
        }
#endif

        /// <summary>
        /// Converts a JSON string into a BrandRegistrationOtpResource object
        /// </summary>
        /// <param name="json"> Raw JSON string </param>
        /// <returns> BrandRegistrationOtpResource object represented by the provided JSON </returns>
        public static BrandRegistrationOtpResource FromJson(string json)
        {
            try
            {
                return JsonConvert.DeserializeObject<BrandRegistrationOtpResource>(json);
            }
            catch (JsonException e)
            {
                throw new ApiException(e.Message, e);
            }
        }


        ///<summary> The SID of the [Account](https://www.kandy.com/docs/iam/api/account) that created the Brand Registration resource. </summary> 
        [JsonProperty("account_sid")]
        public string AccountSid { get; private set; }

        ///<summary> The unique string to identify Brand Registration of Sole Proprietor Brand </summary> 
        [JsonProperty("brand_registration_sid")]
        public string BrandRegistrationSid { get; private set; }



        private BrandRegistrationOtpResource()
        {

        }
    }
}
