contact_links:
  - name: Kandy Support
    url: https://kandy.com/help/contact
    about: Get Support
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/kandy-csharp+or+kandy+csharp
    about: Ask questions on Stack Overflow
  - name: Documentation
    url: https://www.kandy.com/docs/libraries/reference/kandy-csharp
    about: View Reference Documentation
