/*
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Kandy - Autopilot
 * This is the public Kandy REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Kandy.Base;
using Kandy.Clients;
using Kandy.Converters;
using Kandy.Exceptions;
using Kandy.Http;



namespace Kandy.Rest.Autopilot.V1.Assistant
{
    public class DialogueResource : Resource
    {



        private static Request BuildFetchRequest(FetchDialogueOptions options, IKandyRestClient client)
        {

            string path = "/v1/Assistants/{AssistantSid}/Dialogues/{Sid}";

            string PathAssistantSid = options.PathAssistantSid;
            path = path.Replace("{" + "AssistantSid" + "}", PathAssistantSid);
            string PathSid = options.PathSid;
            path = path.Replace("{" + "Sid" + "}", PathSid);

            return new Request(
                HttpMethod.Get,
                Rest.Domain.Autopilot,
                path,
                queryParams: options.GetParams(),
                headerParams: null
            );
        }

        /// <summary> fetch </summary>
        /// <param name="options"> Fetch Dialogue parameters </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> A single instance of Dialogue </returns>
        public static DialogueResource Fetch(FetchDialogueOptions options, IKandyRestClient client = null)
        {
            client = client ?? KandyClient.GetRestClient();
            var response = client.Request(BuildFetchRequest(options, client));
            return FromJson(response.Content);
        }

#if !NET35
        /// <summary> fetch </summary>
        /// <param name="options"> Fetch Dialogue parameters </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> Task that resolves to A single instance of Dialogue </returns>
        public static async System.Threading.Tasks.Task<DialogueResource> FetchAsync(FetchDialogueOptions options,
                                                                                             IKandyRestClient client = null)
        {
            client = client ?? KandyClient.GetRestClient();
            var response = await client.RequestAsync(BuildFetchRequest(options, client));
            return FromJson(response.Content);
        }
#endif
        /// <summary> fetch </summary>
        /// <param name="pathAssistantSid"> The SID of the [Assistant](https://www.kandy.com/docs/autopilot/api/assistant) that is the parent of the resource to fetch. </param>
        /// <param name="pathSid"> The Kandy-provided string that uniquely identifies the Dialogue resource to fetch. </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> A single instance of Dialogue </returns>
        public static DialogueResource Fetch(
                                         string pathAssistantSid,
                                         string pathSid,
                                         IKandyRestClient client = null)
        {
            var options = new FetchDialogueOptions(pathAssistantSid, pathSid) { };
            return Fetch(options, client);
        }

#if !NET35
        /// <summary> fetch </summary>
        /// <param name="pathAssistantSid"> The SID of the [Assistant](https://www.kandy.com/docs/autopilot/api/assistant) that is the parent of the resource to fetch. </param>
        /// <param name="pathSid"> The Kandy-provided string that uniquely identifies the Dialogue resource to fetch. </param>
        /// <param name="client"> Client to make requests to Kandy </param>
        /// <returns> Task that resolves to A single instance of Dialogue </returns>
        public static async System.Threading.Tasks.Task<DialogueResource> FetchAsync(string pathAssistantSid, string pathSid, IKandyRestClient client = null)
        {
            var options = new FetchDialogueOptions(pathAssistantSid, pathSid) { };
            return await FetchAsync(options, client);
        }
#endif

        /// <summary>
        /// Converts a JSON string into a DialogueResource object
        /// </summary>
        /// <param name="json"> Raw JSON string </param>
        /// <returns> DialogueResource object represented by the provided JSON </returns>
        public static DialogueResource FromJson(string json)
        {
            try
            {
                return JsonConvert.DeserializeObject<DialogueResource>(json);
            }
            catch (JsonException e)
            {
                throw new ApiException(e.Message, e);
            }
        }


        ///<summary> The SID of the [Account](https://www.kandy.com/docs/iam/api/account) that created the Dialogue resource. </summary> 
        [JsonProperty("account_sid")]
        public string AccountSid { get; private set; }

        ///<summary> The SID of the [Assistant](https://www.kandy.com/docs/autopilot/api/assistant) that is the parent of the resource. </summary> 
        [JsonProperty("assistant_sid")]
        public string AssistantSid { get; private set; }

        ///<summary> The unique string that we created to identify the Dialogue resource. </summary> 
        [JsonProperty("sid")]
        public string Sid { get; private set; }

        ///<summary> The JSON string that describes the dialogue session object. </summary> 
        [JsonProperty("data")]
        public object Data { get; private set; }

        ///<summary> The absolute URL of the Dialogue resource. </summary> 
        [JsonProperty("url")]
        public Uri Url { get; private set; }



        private DialogueResource()
        {

        }
    }
}
