name: Test and Deploy
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: [main]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: "0 15 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout kandy-csharp
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "3.1.x"

      - name: Build & Test
        run: make test
