name: Test and Deploy
on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: [main]
  schedule:
    # Run automatically at 8AM PST Monday-Friday
    - cron: "0 15 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout kandy-csharp
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "3.1.x"

      - name: Build & Test
        run: make test

      - name: Install SonarCloud scanner and run analysis
        if: (github.event_name == 'pull_request' || github.ref_type == 'branch') && !github.event.pull_request.head.repo.fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          KANDY_ACCOUNT_SID: ${{ secrets.KANDY_ACCOUNT_SID }}
          KANDY_API_KEY: ${{ secrets.KANDY_CLUSTER_TEST_API_KEY }}
          KANDY_API_SECRET: ${{ secrets.KANDY_CLUSTER_TEST_API_KEY_SECRET }}
          KANDY_FROM_NUMBER: ${{ secrets.KANDY_FROM_NUMBER }}
          KANDY_TO_NUMBER: ${{ secrets.KANDY_TO_NUMBER }}
        run: |
          dotnet tool install --global dotnet-sonarscanner
          make cover
